#!/bin/sh

# aureus-setup-anchor
if [ "$AUREUS_INTERNAL_PUSH" = "true" ]; then
  exit 0
fi

if npx aureus bump; then
  # bump created a new commit — push everything including the bump, then cancel original push
  AUREUS_INTERNAL_PUSH=true git push && exit 0
fi

exit 0
